# Generated by Django 5.1.2 on 2024-10-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
