# Generated by Django 5.1.5 on 2025-01-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drugs',
            new_name='Drug',
        ),
    ]
